apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    app: influxdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  storageClassName: manual
  volumeName: influxdb-pv
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: influxdb-pv-storage
          persistentVolumeClaim:
            claimName: influxdb-pvc
      containers: 
        - name: influxdb
          image: influxdb-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: dockersock
            - name: influxdb-pv-storage
              mountPath: "/root/.influxdb"
  replicas: 1
  selector:
    matchLabels:
      app: influxdb