apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysqlPod
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessMode:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  storageClassName: manual
  volumeName: mysql-pv
  resources:
    requests:
      storage: 1Gi
  accessMode:
  - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysqlPod
        type: mysql
    spec:
      containers: 
        - name: mysql_container
          image: mysql-image
          imagePullPolicy: Never
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql_container
  replicas: 1
  selector:
    matchLabels:
      app: mysql