# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-svc
#   annotations:
#     metallb.universe.tf/allow-shared-ip: shared
# spec:
#   selector:
#     app: nginx
#   type: LoadBalancer
#   loadBalancerIP: 192.168.99.139
#   ports:
#     - protocol: TCP
#       name: http
#       port: 80
#       targetPort: 80
#     - protocol: TCP
#       name: https
#       port: 443
#       targetPort: 443

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx-image
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 80
#         - containerPort: 443

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: nginxPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeploy
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginxPod
        type: nginx
    spec:
      containers: 
        - name: nginxcontainer
          image: nginx-image
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
  replicas: 1
  selector:
    matchLabels:
      app: nginxPod
      type: nginx