apiVersion: v1
kind: Service
metadata:
  name: phpma
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: mysqlPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpma-deploy
spec:
  template:
    metadata:
      name: phpma-pod
      labels:
        app: mysqlPod
        type: phpma
    spec:
      containers: 
        - name: phpma-container
          image: phpma-image
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5000
  replicas: 1
  selector:
    matchLabels:
      app: mysqlPod
      type: phpma