apiVersion: v1
kind: Service
metadata:
  name: wp
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
spec:
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers: 
        - name: wp
          image: wp-image
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
  replicas: 1
  selector:
    matchLabels:
      app: wp