apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: ftp
    protocol: TCP
    port: 20
    targetPort: 20
  - name: ftps
    protocol: TCP
    port: 21
    targetPort: 21
  - name: psv1
    protocol: TCP
    port: 31000
    targetPort: 31000
  - name: psv2
    protocol: TCP
    port: 31001
    targetPort: 31001
  - name: psv3
    protocol: TCP
    port: 31002
    targetPort: 31002
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers: 
        - name: ftps
          image: ftps-image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 31000
            - containerPort: 31001
            - containerPort: 31002
  replicas: 1
  selector:
    matchLabels:
      app: ftps